### ISSUE TITLE
Compatibility with Clickhouse

### ISSUE THREAD

**Issue by jakejh** [hugheylab/pmparser#33]
- [ ] test parsing functions
- [ ] test `unark`, which is used by `getCitation`
- [x] update `connect`, making sure to use `db = dbname`
- [x] update `deleteOldPmidVersions` - Clickhouse doesn't have window functions, so try [rowNumberInAllBlocks](https://clickhouse.tech/docs/en/sql-reference/functions/other-functions/#rownumberinallblocks)
- [x] update `addSourceToTarget` - try rowNumberInAllBlocks and change [delete statements](https://clickhouse.tech/docs/en/sql-reference/statements/alter/delete/)
- [x] update `runStatement` for Clickhouse delete statements
- [ ] test speed of various queries on database
- [ ] test clickhouse [backup and restore](https://github.com/AlexAkulov/clickhouse-backup)
- [ ] update documentation
- [ ] update `pkgdown` site
- [ ] possibly add clickhouse dump to Zenodo repo along with instructions for restoring it

**Comment by jakejh** [comment]
Soon we'll be able to use `dbname` instead of `db`.

https://github.com/IMSMWU/RClickhouse/issues/69

**Comment by JSchoenbachler** [comment]
I have pushed many of my updates and merged with some of the pull requests this morning. Going to be testing to make sure it is working properly.

**Comment by danielw2904** [comment]
We have merged the parameter name change. Could you test with our master branch and let us know if something is not working?

**Comment by jakejh** [comment]
@JSchoenbachler Can we close this issue for now?

**Comment by JSchoenbachler** [comment]
Yep, closing!
