### ISSUE TITLE
checking for connection class

### ISSUE THREAD

**Issue by jakejh** [hugheylab/pmparser#37]
Use `inherits` instead of `class`. The former is robust to a class of length > 1. We have a couple examples of this in the code already.

https://github.com/hugheylab/pmparser/blob/136ae52e67e13f5b1c324ef03612bba1b7a70570/R/utilities.R#L68

**Comment by JSchoenbachler** [comment]
Fixed as of this comit: https://github.com/hugheylab/pmparser/commit/ef81fc50dacc90eb7a71edcfedb0cb4ba55ca1e9
