### ISSUE TITLE
PMDB stopped releasing new versions

### ISSUE THREAD

**Issue by sitch** [hugheylab/pmparser#48]
The latest version on zenodo is from October 9 2021 https://zenodo.org/record/5559146/

Anyway I can help?

**Comment by jakejh** [comment]
Hi @sitch , sorry about that. We've been working on a couple grants and didn't have time to debug some issues that came up when trying to update the DB. I'm working on this now and hope to have an updated PMDB by the end of the week.

**Comment by jakejh** [comment]
Ok, PMDB is now updated on Zenodo: https://zenodo.org/record/5879035

Enjoy!
