### ISSUE TITLE
Indexes

### ISSUE THREAD

**Issue by globbestael** [hugheylab/pmparser#49]
Hi,
Wonderful tool! 
Question: Is there an overview of the indexes needed / which you have found useful?
best regards, geert

**Comment by jakejh** [comment]
Do you mean indexes in the Postgres db? @JSchoenbachler What are your thoughts?

**Comment by globbestael** [comment]
Hi Josh,
Thank you for the extensive answer. It certainly is useful.
I hadn't seen https://github.com/hugheylab/publication_path yet.

best regards, geert
