### ISSUE TITLE
Missing BQ tables?

### ISSUE THREAD

**Issue by ravwojdyla** [hugheylab/pmparser#84]
We have noticed that right now there's only 2 tables in the `pmdb-bq.pmdb` dataset:

![image](https://github.com/hugheylab/pmparser/assets/1419010/f04c41e4-d2f8-4a69-8aa5-d89c44329efa)

Is this expected? Has the data been moved somewhere else?

Last modified data of one of the tables is very recent: 17th of May, maybe the BQ load failed?

**Comment by jakejh** [comment]
Oh sorry about that. I was in a place with really slow upload speed, so I aborted the transfer from postgres. My ETL scripts aren't ideal, so the previous version wasn't preserved. The upload of the latest version just finished, so let me know if it's working for you.

**Comment by ravwojdyla** [comment]
@jakejh thank you so much! BQ looks much better now. Kicked off our ETLs, will close this issue when they finish.

**Comment by ravwojdyla** [comment]
Looks good on our side. Closing. Thank you again @jakejh
