### ISSUE TITLE
Monthly PMDB Updates on Zenodo discontinued?

### ISSUE THREAD

**Issue by KimBenjaminTang** [hugheylab/pmparser#86]
Hello Hughey Lab team, 

are the monthly updates of the PMDB Dump on Zenodo discontinued or on pause?
As of right now, the most recent dump was uploaded in August and I was wondering whether a version for october 2023 with citable DOI would be uploaded. 

Best regards,
Kim

**Comment by jakejh** [comment]
Hi Kim, uploads on Zenodo's new interface are failing, so I've asked their customer support for help.

**Comment by KimBenjaminTang** [comment]
Hi Jake, okay thanks for the info. Hope it can be resolved

**Comment by jakejh** [comment]
PMDB on Zenodo is now up-to-date: https://doi.org/10.5281/zenodo.10009644
