### ISSUE TITLE
Abstract(s) missing for publication

### ISSUE THREAD

**Issue by KimBenjaminTang** [hugheylab/pmparser#87]
Hello,

I wanted to retrieve the abstract for the publication with PMID: 5912471 from PMDB (local/Google Big Query) but no data was returned.

For this publication, abstracts in three languages are available online in PubMed:
![grafik](https://github.com/hugheylab/pmparser/assets/16795915/8bf94e10-cd5c-478e-bf44-826bf8369a23)
 
And the content can also be retrieved via the Entrez API:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=5912471&retmode=xml&rettype=abstract

When I search for the publication via Google Query in PMDB, the metadata can be retrieved from the article table:
![grafik](https://github.com/hugheylab/pmparser/assets/16795915/13841c65-9207-439e-9d51-6bd9fbf29135)

But unfortunately nothing is found for this publication in "abstract" or "otherAbstract":
![grafik](https://github.com/hugheylab/pmparser/assets/16795915/6504a928-7231-4e66-94da-4dc18dffe204)

Perhaps this is related to this previous issue? https://github.com/hugheylab/pmparser/issues/71 

Is it a parsing error ? I also thought that the abstract might simply not be in the XML files used for parsing the data, but since its a Medline citation I think it should be included.

**Comment by jakejh** [comment]
In this case, it's not a parsing error. I checked the baseline XML file (pubmed23n0197.xml) [here](https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/), and it actually does not contain any of the abstracts for pmid 5912471. I'm not sure why.

**Comment by KimBenjaminTang** [comment]
Okay, thanks for the help! It is very useful that pmparser/PMDB keeps track of the parsed XML file for each PMID to be able to compare data with the original files. 

I contacted the NLM support to ask for clarification and figured it is helpful to share the answer here also for others:

![grafik](https://github.com/hugheylab/pmparser/assets/16795915/78ffd3e2-40d6-4b5a-ac84-3d28a5138111)

Essentially as of right now, the data provided in the XML files (FTP) is not exactly the same data as provided by the E-Utilities API or PubMed online, but that should change in the future.
